import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import konfigurasi.koneksi;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ACER
 */
public class FormBuku extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormBuku.class.getName());

    /**
     * Creates new form FormBuku
     */
    public FormBuku() {
        initComponents();
        tampilkanData(); // Ditambahkan di sini agar dipanggil saat aplikasi jalan
    }

    private void tampilkanData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Buku");
        model.addColumn("Judul Buku");
        model.addColumn("Harga");
        model.addColumn("Stok");
        
        try {
            Connection conn = koneksi.getConfig();
            Statement st = conn.createStatement();
            String query = "SELECT * FROM tb_buku";
            ResultSet rs = st.executeQuery(query);
            
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_buku"),
                    rs.getString("judul_buku"),
                    rs.getString("harga"),
                    rs.getString("stok")
                });
            }
            
            // PASTIKAN nama variabel JTable kamu di tab Design adalah "tabelDataBuku"
            tabelDataBuku.setModel(model); 
            
        } catch (Exception e) {
            System.out.println("Gagal memuat data ke tabel: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtJudul = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelDataBuku = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("FORM KELOLA DATA BUKU");

        jLabel2.setText("ID BUKU");

        jLabel3.setText("JUDUL BUKU");

        jLabel4.setText("HARGA");

        jLabel5.setText("STOK");

        txtJudul.addActionListener(this::txtJudulActionPerformed);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        tabelDataBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelDataBuku);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnCetak.setText("Cetak Laporan");
        btnCetak.addActionListener(this::btnCetakActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtJudul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHarga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(381, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus)))
                        .addGap(103, 103, 103))))
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(btnCetak)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnEdit)
                    .addComponent(btnHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCetak)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJudulActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
String id = txtID.getText();
    String judul = txtJudul.getText();
    String harga = txtHarga.getText();
    String stok = txtStock.getText();
    
    // Memastikan form tidak ada yang kosong saat diklik simpan
    if (id.equals("") || judul.equals("") || harga.equals("") || stok.equals("")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Semua kolom wajib diisi!");
    } else {
        try {
            // Query SQL untuk menyimpan data ke tabel tb_buku
            // 'K001' dimasukkan sementara sebagai contoh id_kategori yang valid
            String sql = "INSERT INTO tb_buku (id_buku, judul_buku, id_kategori, harga, stok) "
                       + "VALUES ('" + id + "', '" + judul + "', 'K001', '" + harga + "', '" + stok + "')";
            
            java.sql.Connection conn = konfigurasi.koneksi.getConfig();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            
            // Notifikasi sukses
            javax.swing.JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan!");
            
            // Membersihkan kolom inputan setelah sukses menyimpan
            txtID.setText("");
            txtJudul.setText("");
            txtHarga.setText("");
            txtStock.setText("");
            
            // Memanggil kembali fungsi tampilkanData() agar JTable otomatis terupdate
            tampilkanData();
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
        }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
    String id = txtID.getText();
String judul = txtJudul.getText();
String harga = txtHarga.getText();
String stok = txtStock.getText();

if (id.equals("") || judul.equals("") || harga.equals("") || stok.equals("")) {
    javax.swing.JOptionPane.showMessageDialog(this, "Pilih atau isi data yang ingin diubah!");
} else {
    try {
        // Query SQL untuk mengubah data berdasarkan id_buku
        String sql = "UPDATE tb_buku SET judul_buku='" + judul + "', harga='" + harga + "', stok='" + stok + "' WHERE id_buku='" + id + "'";
        
        java.sql.Connection conn = konfigurasi.koneksi.getConfig();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.execute();
        
        javax.swing.JOptionPane.showMessageDialog(null, "Data Berhasil Diubah!");
        
        // Kosongkan form setelah edit sukses
        txtID.setText("");
        txtJudul.setText("");
        txtHarga.setText("");
        txtStock.setText("");
        
        // Refresh tabel agar data terbaru langsung muncul
        tampilkanData();
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal mengubah data: " + e.getMessage());
    }
}
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
try {
    String html = "<html>"
            + "<head>"
            + "<title>Data Toko Buku</title>"
            + "<style>"
            + "table{border-collapse:collapse;width:100%;}"
            + "th,td{border:1px solid black;padding:8px;text-align:left;}"
            + "th{background:#cccccc;}"
            + "</style>"
            + "</head>"
            + "<body>";
    html += "<h2 align='center'>LAPORAN DATA TOKO BUKU</h2>";
    html += "<table>";
    html += "<tr>"
            + "<th>ID Buku</th>"
            + "<th>Judul Buku</th>"
            + "<th>Harga</th>"
            + "<th>Stok</th>"
            + "</tr>";
            
    for (int i = 0; i < tabelDataBuku.getRowCount(); i++) {
        html += "<tr>";
        for (int j = 0; j < tabelDataBuku.getColumnCount(); j++) {
            html += "<td>"
                    + tabelDataBuku.getValueAt(i, j)
                    + "</td>";
        }
        html += "</tr>";
    }
    html += "</table>";
    html += "</body></html>";
    
    java.io.File file = new java.io.File("laporan_buku.html");
    java.io.FileWriter fw = new java.io.FileWriter(file);
    fw.write(html);
    fw.close();
    
    java.awt.Desktop.getDesktop().browse(file.toURI());
    
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(null,
            "Gagal membuat laporan : "
            + e.getMessage());
}
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
String id = txtID.getText();

if (id.equals("")) {
    javax.swing.JOptionPane.showMessageDialog(this, "Isi atau pilih ID Buku yang ingin dihapus!");
} else {
    // Memunculkan konfirmasi yakin/tidak sebelum menghapus data
    int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data ini?", "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
        try {
            // Query SQL untuk menghapus data berdasarkan id_buku
            String sql = "DELETE FROM tb_buku WHERE id_buku='" + id + "'";
            
            java.sql.Connection conn = konfigurasi.koneksi.getConfig();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            
            javax.swing.JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus!");
            
            // Kosongkan form setelah hapus sukses
            txtID.setText("");
            txtJudul.setText("");
            txtHarga.setText("");
            txtStock.setText("");
            
            // Refresh tabel
            tampilkanData();
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + e.getMessage());
        }
    }
}
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormBuku().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabelDataBuku;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
